from dataclasses import dataclass, field
from typing import Optional
from .enums import Role


@dataclass
class User:
    """Authenticated user with profile data from Supabase.
    
    The `id` field maps to auth.users.id (UUID).
    The `role` determines which features are accessible.
    `first_name` is used for greetings instead of hardcoded names.
    """
    id: str  # UUID from auth.users
    email: str
    first_name: str
    last_name: str
    role: Role
    business_id: str  # Every user belongs to exactly one business
    phone: str = ""

    @property
    def display_name(self) -> str:
        return self.first_name

    @property
    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"


@dataclass
class Business:
    """A business entity that owns all data.
    
    Every user belongs to exactly one business.
    All records (sales, inventory, customers, etc.) reference business_id.
    """
    id: str
    name: str
    created_at: str = ""
    owner_id: str = ""


@dataclass
class Invitation:
    """An invitation code for joining a business.
    
    Generated by the business owner.
    Expires after 24 hours.
    Once used, is_invalidated = True.
    owner_invite: True → co-owner invitation, False → worker invitation
    """
    code: str
    business_id: str
    email: str = ""
    created_at: str = ""
    expires_at: str = ""
    is_invalidated: bool = False
    owner_invite: bool = False
